<?php

return [
    [
        'key'    => 'victor_mer',
        'name'   => 'victor_mer::app.system.victor-mer',
        'info'   => 'victor_mer::app.system.victor-mer-info',
        'sort'   => 1,
        'fields' => [
            [
                'key'    => 'victor_mer.general',
                'name'   => 'victor_mer::app.system.general.title',
                'info'   => 'victor_mer::app.system.general.info',
                'icon'   => 'settings/general.svg',
                'sort'   => 1,
                'fields' => [
                    [
                        'name'          => 'site_name',
                        'title'         => 'victor_mer::app.system.general.site-name',
                        'type'          => 'text',
                        'validation'    => 'required',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'site_email',
                        'title'         => 'victor_mer::app.system.general.site-email',
                        'type'          => 'text',
                        'validation'    => 'required|email',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'site_phone',
                        'title'         => 'victor_mer::app.system.general.site-phone',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'site_address',
                        'title'         => 'victor_mer::app.system.general.site-address',
                        'type'          => 'textarea',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'site_logo',
                        'title'         => 'victor_mer::app.system.general.site-logo',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'site_favicon',
                        'title'         => 'victor_mer::app.system.general.site-favicon',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                ],
            ],
            [
                'key'    => 'victor_mer.seo',
                'name'   => 'victor_mer::app.system.seo.title',
                'info'   => 'victor_mer::app.system.seo.info',
                'icon'   => 'settings/seo.svg',
                'sort'   => 2,
                'fields' => [
                    [
                        'name'          => 'seo_title',
                        'title'         => 'victor_mer::app.system.seo.seo-title',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'seo_description',
                        'title'         => 'victor_mer::app.system.seo.seo-description',
                        'type'          => 'textarea',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'seo_keywords',
                        'title'         => 'victor_mer::app.system.seo.seo-keywords',
                        'type'          => 'textarea',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'seo_og_title',
                        'title'         => 'victor_mer::app.system.seo.og-title',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'seo_og_description',
                        'title'         => 'victor_mer::app.system.seo.og-description',
                        'type'          => 'textarea',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'seo_og_image',
                        'title'         => 'victor_mer::app.system.seo.og-image',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'google_analytics',
                        'title'         => 'victor_mer::app.system.seo.google-analytics',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'google_tag_manager',
                        'title'         => 'victor_mer::app.system.seo.google-tag-manager',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                    [
                        'name'          => 'facebook_pixel',
                        'title'         => 'victor_mer::app.system.seo.facebook-pixel',
                        'type'          => 'text',
                        'channel_based' => false,
                        'locale_based'  => false,
                    ],
                ],
            ],
            [
                'key'    => 'victor_mer.dashboard',
                'name'   => 'victor_mer::app.system.dashboard.title',
                'info'   => 'victor_mer::app.system.dashboard.info',
                'icon'   => 'settings/dashboard.svg',
                'sort'   => 3,
                'fields' => [],
            ],
        ],
    ],
];
