<?php

namespace Webkul\B2BSuite\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanyRolesTableSeeder extends Seeder
{
    public function run(array $parameters = [])
    {
        DB::table('company_roles')->truncate();

        $now = $parameters['now'] ?? now()->toDateTimeString();

        $roles = [
            [
                'id'              => 1,
                'name'            => 'Company Administrator',
                'description'     => 'Full access to all company features and settings',
                'permission_type' => 'all',
                'permissions'     => json_encode(['*']),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 2,
                'name'            => 'Procurement Manager',
                'description'     => 'Manages purchasing, suppliers, and procurement processes',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'orders.create',
                    'orders.view',
                    'orders.edit',
                    'suppliers.manage',
                    'products.view',
                    'quotes.manage',
                    'budgets.view',
                    'reports.procurement',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 3,
                'name'            => 'Sales Manager',
                'description'     => 'Manages sales activities, quotes, and customer relationships',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'quotes.create',
                    'quotes.view',
                    'quotes.edit',
                    'quotes.approve',
                    'customers.manage',
                    'orders.view',
                    'reports.sales',
                    'discounts.manage',
                    'pricing.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 4,
                'name'            => 'Finance Manager',
                'description'     => 'Handles financial operations, budgets, and payment approvals',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'budgets.manage',
                    'payments.approve',
                    'invoices.manage',
                    'reports.financial',
                    'orders.approve',
                    'credit.manage',
                    'expenses.view',
                    'accounting.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 5,
                'name'            => 'Department Head',
                'description'     => 'Departmental oversight with limited administrative access',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'orders.create',
                    'orders.view',
                    'orders.approve',
                    'budgets.view',
                    'users.view',
                    'users.manage',
                    'reports.department',
                    'products.view',
                    'team.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 6,
                'name'            => 'Buyer',
                'description'     => 'Can create and manage purchase orders within approved budgets',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'orders.create',
                    'orders.view',
                    'orders.edit',
                    'products.view',
                    'suppliers.view',
                    'quotes.request',
                    'quotes.view',
                    'budgets.view',
                    'cart.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 7,
                'name'            => 'Approver',
                'description'     => 'Reviews and approves orders, quotes, and purchase requests',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'orders.approve',
                    'orders.reject',
                    'quotes.approve',
                    'quotes.reject',
                    'budgets.approve',
                    'orders.view',
                    'quotes.view',
                    'reports.approval',
                    'workflow.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 8,
                'name'            => 'Inventory Manager',
                'description'     => 'Manages stock levels, warehouse operations, and product catalog',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'inventory.manage',
                    'products.manage',
                    'warehouses.manage',
                    'suppliers.view',
                    'suppliers.manage',
                    'reports.inventory',
                    'orders.view',
                    'stock.manage',
                    'catalog.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 9,
                'name'            => 'Account Manager',
                'description'     => 'Manages customer accounts and relationships',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'customers.manage',
                    'customers.view',
                    'quotes.create',
                    'quotes.view',
                    'orders.view',
                    'reports.customer',
                    'discounts.apply',
                    'pricing.view',
                    'relationships.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 10,
                'name'            => 'Employee',
                'description'     => 'Basic access for regular company employees',
                'permission_type' => 'limited',
                'permissions'     => json_encode([
                    'products.view',
                    'orders.create',
                    'orders.view_own',
                    'profile.edit',
                    'budgets.view',
                    'catalog.browse',
                    'cart.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 11,
                'name'            => 'Guest',
                'description'     => 'Limited access for external users or temporary access',
                'permission_type' => 'restricted',
                'permissions'     => json_encode([
                    'products.view',
                    'catalog.browse',
                    'quotes.request',
                    'profile.view',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'id'              => 12,
                'name'            => 'Vendor Manager',
                'description'     => 'Manages vendor relationships and supplier operations',
                'permission_type' => 'custom',
                'permissions'     => json_encode([
                    'suppliers.manage',
                    'suppliers.view',
                    'vendor.onboard',
                    'vendor.evaluate',
                    'contracts.manage',
                    'procurement.negotiate',
                    'reports.vendor',
                    'products.view',
                    'quotes.manage',
                ]),
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
        ];

        DB::table('company_roles')->insert($roles);
    }
}
